//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace WeUiSharp.Demo.Properties {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("WeUiSharp.Demo.Properties.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   重写当前线程的 CurrentUICulture 属性，对
        ///   使用此强类型资源类的所有资源查找执行重写。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 登录 的本地化字符串。
        /// </summary>
        public static string ButtonLogin {
            get {
                return ResourceManager.GetString("ButtonLogin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 设置 的本地化字符串。
        /// </summary>
        public static string Settings {
            get {
                return ResourceManager.GetString("Settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 这是一段测试文本。 的本地化字符串。
        /// </summary>
        public static string TestText {
            get {
                return ResourceManager.GetString("TestText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 关于 的本地化字符串。
        /// </summary>
        public static string TextAbout {
            get {
                return ResourceManager.GetString("TextAbout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 你的自定义Alert消息 的本地化字符串。
        /// </summary>
        public static string TextAlertMessage {
            get {
                return ResourceManager.GetString("TextAlertMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 通用设置 的本地化字符串。
        /// </summary>
        public static string TextCommonSettings {
            get {
                return ResourceManager.GetString("TextCommonSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 语言 的本地化字符串。
        /// </summary>
        public static string TextLanguage {
            get {
                return ResourceManager.GetString("TextLanguage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 更多 的本地化字符串。
        /// </summary>
        public static string TextMore {
            get {
                return ResourceManager.GetString("TextMore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 仅传输文件 的本地化字符串。
        /// </summary>
        public static string TextOnlyTransferFiles {
            get {
                return ResourceManager.GetString("TextOnlyTransferFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 其它 的本地化字符串。
        /// </summary>
        public static string TextOthers {
            get {
                return ResourceManager.GetString("TextOthers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 你的自定义设置选项 的本地化字符串。
        /// </summary>
        public static string TextSettingsOption {
            get {
                return ResourceManager.GetString("TextSettingsOption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 切换帐号 的本地化字符串。
        /// </summary>
        public static string TextSwitchAccount {
            get {
                return ResourceManager.GetString("TextSwitchAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 ▪ 微信公众号： 的本地化字符串。
        /// </summary>
        public static string TextWechatOfficialAccount {
            get {
                return ResourceManager.GetString("TextWechatOfficialAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 微信 的本地化字符串。
        /// </summary>
        public static string WeChat {
            get {
                return ResourceManager.GetString("WeChat", resourceCulture);
            }
        }
    }
}
